In [1]:
import numpy as np
from math import acos, degrees

A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])

A_plus_B = A + B
twoA_plus_threeB = 2 * A + 3 * B

dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_degrees = round(degrees(acos(cos_theta)), 3)

C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])
C_CT = np.dot(C, C.T)

print( "A + B =", A_plus_B)
print(" 2A + 3B =", twoA_plus_threeB)
print(" A · B =", dot_product)
print(" Angle between A and B (degrees) =", angle_degrees)
print(" C * C^T =\n", C_CT)


a) A + B = [2 3 1 6]
a) 2A + 3B = [ 3 11  2 14]
b) A · B = -5
b) Angle between A and B (degrees) = 99.594
c) C * C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [2]:
import numpy as np

M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

product_MN = np.dot(M, N)

try:
    det_M = np.linalg.det(M)
    det_M_result = round(det_M, 3)
except np.linalg.LinAlgError:
    det_M_result = "Không khả thi (ma trận không vuông)"

rank_N = np.linalg.matrix_rank(N)

print(" M × N =\n", product_MN)
print(" det(M) =", det_M_result)
print(" rank(N) =", rank_N)


 M × N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
 det(M) = 409.0
 rank(N) = 4


In [3]:
import numpy as np

P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])

B = np.array([6, 8, 3, 7])

try:
    P_inv = np.linalg.inv(P)
    is_invertible = True
except np.linalg.LinAlgError:
    P_inv = None
    is_invertible = False

if is_invertible:
    solution = np.dot(P_inv, B)
else:
    solution = "Không giải được bằng nghịch đảo (ma trận không khả nghịch)"

if is_invertible:
    check_result = np.dot(P, solution)
else:
    check_result = None

print("Ma trận nghịch đảo của P =\n", P_inv)
print(" Nghiệm của hệ phương trình =", solution)
print(" P * nghiệm =", check_result)


Ma trận nghịch đảo của P =
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
 Nghiệm của hệ phương trình = [2.         1.71428571 0.42857143 0.85714286]
 P * nghiệm = [6. 8. 3. 7.]


In [4]:
import numpy as np

Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

eigenvalues, eigenvectors = np.linalg.eig(Q)
eigenvectors_list = eigenvectors.T.tolist()
normalized_vectors = [vec / np.linalg.norm(vec) for vec in eigenvectors.T]

print(" Giá trị riêng:", eigenvalues)
print(" Vector riêng:")
for vec in eigenvectors_list:
    print(vec)
print(" Vector riêng chuẩn hóa:")
for vec in normalized_vectors:
    print(vec)


 Giá trị riêng: [6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]
 Vector riêng:
[(0.7484601259210814+0j), (-0.18941773383060273+0j), (0.6355535870535844+0j)]
[(-0.37423006296054073+0.3423421513016493j), (0.09470886691530005+0.5743305493612973j), (0.6355535870535848+0j)]
[(-0.37423006296054073-0.3423421513016493j), (0.09470886691530005-0.5743305493612973j), (0.6355535870535848-0j)]
 Vector riêng chuẩn hóa:
[ 0.74846013+0.j -0.18941773+0.j  0.63555359+0.j]
[-0.37423006+0.34234215j  0.09470887+0.57433055j  0.63555359+0.j        ]
[-0.37423006-0.34234215j  0.09470887-0.57433055j  0.63555359-0.j        ]


In [5]:
import numpy as np

R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])

x1 = np.linalg.solve(R, b)

try:
    R_inv = np.linalg.inv(R)
    x2 = np.dot(R_inv, b)
except np.linalg.LinAlgError:
    R_inv = None
    x2 = None

frobenius_norm = np.linalg.norm(R, 'fro')

print(" Nghiệm hệ Rx = b:", x1)
if R_inv is not None:
    print(" Ma trận nghịch đảo của R:\n", R_inv)
    print(" Nghiệm từ nghịch đảo:", x2)
else:
    print(" R không khả nghịch")
print(" Chuẩn Frobenius của R:", round(frobenius_norm, 3))


 Nghiệm hệ Rx = b: [2.78823529 1.52941176 1.18823529]
 Ma trận nghịch đảo của R:
 [[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
 Nghiệm từ nghịch đảo: [2.78823529 1.52941176 1.18823529]
 Chuẩn Frobenius của R: 8.0
