bài tập trên lớp


In [ ]:
import numpy as np

# Use np.array instead of just array
np.array([1, 2, 3])



array([1, 2, 3])

In [ ]:
# Use np.array instead of just array
import numpy as np

np.array([1, 2, 3])

np.array([[(1+9j), 0.+2.j, 0.+3.j],
       [0.+4.j, 0.+5.j, 0.+6.j]])


array([[1.+9.j, 0.+2.j, 0.+3.j],
       [0.+4.j, 0.+5.j, 0.+6.j]])

In [ ]:
# Use np.array instead of just array
# The array function is part of the numpy library and needs to be called using np.
np.array([[[0.5, 1.5, 10. ],
        [3. , 2. , 1. ]],

       [[6. , 5. , 4. ],
        [7. , 8. , 9. ]]])

array([[[ 0.5,  1.5, 10. ],
        [ 3. ,  2. ,  1. ]],

       [[ 6. ,  5. ,  4. ],
        [ 7. ,  8. ,  9. ]]])

In [ ]:
# Use np.array instead of just array
# The array function is part of the numpy library and needs to be called using np.
import numpy as np # Ensure numpy is imported

np.array([[[0.5, 1.5, 10. ],
        [3. , 2. , 1. ]],

       [[6. , 5. , 4. ],
        [7. , 8. , 9. ]]])

# Call the matrix function using the np. prefix
np.matrix([[0.743, 0.181],
        [0.234, 0.997]])  # ví dụ, giá trị thực tế sẽ khác mỗi lần chạy

matrix([[0.743, 0.181],
        [0.234, 0.997]])

In [ ]:
# Use the np. prefix to call the matrix function from numpy
np.matrix([[(1+9j), 0.+2.j, 0.+3.j],
        [0.+4.j, 0.+5.j, 0.+6.j]])

matrix([[1.+9.j, 0.+2.j, 0.+3.j],
        [0.+4.j, 0.+5.j, 0.+6.j]])

In [ ]:
# Use the np. prefix to call the matrix function from numpy
np.matrix([[0.154, 0.945, 0.132], # Note: '...' is not valid Python syntax within a list
        [0.331, 0.785, 0.902]]) # Replace '...' with actual values or generate them

matrix([[0.154, 0.945, 0.132],
        [0.331, 0.785, 0.902]])

In [ ]:
# Use the np. prefix to call the matrix function from numpy
# The matrix function is part of the numpy library and needs to be called using np.
np.matrix([[4, 3],
        [2, 6]])

matrix([[4, 3],
        [2, 6]])

In [ ]:
import numpy as np # Import the numpy library

# Use np.array instead of just array
np.array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
import numpy as np
from scipy import linalg

# Tạo ma trận ví dụ
A = np.matrix([[4, 3], [2, 6]])
# Use np.asmatrix instead of np.mat as recommended in the error message
C = np.asmatrix(np.random.random((10,5)))

# Ma trận đơn vị k=0
F0 = np.eye(3, k=0)
print("F = np.eye(3, k=0):\n", F0)

# Ma trận đơn vị k=-1
F1 = np.eye(3, k=-1)
print("\nF = np.eye(3, k=-1):\n", F1)

# Hạng của ma trận
print("\nRank of C:", np.linalg.matrix_rank(C))

# Ma trận nghịch đảo
print("\nA.I:\n", A.I)
print("\nscipy.linalg.inv(A):\n", linalg.inv(A))

# Định thức
print("\ndet(A):", linalg.det(A))

# Chuyển vị
print("\nA.T:\n", A.T)

# Chuyển vị liên hợp
print("\nA.H:\n", A.H)

F = np.eye(3, k=0):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

F = np.eye(3, k=-1):
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

Rank of C: 5

A.I:
 [[ 0.33333333 -0.16666667]
 [-0.11111111  0.22222222]]

scipy.linalg.inv(A):
 [[ 0.33333333 -0.16666667]
 [-0.11111111  0.22222222]]

det(A): 18.0

A.T:
 [[4 2]
 [3 6]]

A.H:
 [[4 2]
 [3 6]]


In [ ]:
import numpy as np
from scipy import linalg

# Khởi tạo dữ liệu
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
A = np.array([[4, 3], [2, 6]])
D = np.array([[4, 3], [2, 6]])
F = np.eye(3, k=0)  # ma trận đơn vị 3x3
# E = np.mat(a).T     # chuyển vector a thành ma trận cột - Chức năng này đã bị xóa trong numpy 2.0
E = np.asmatrix(a).T # Use np.asmatrix instead of np.mat

# Giải hệ phương trình A·x = b[:, 0:2]
print("linalg.solve(A, b[:, 0:2]):")
print(linalg.solve(A, b[:, 0:2]))
print()

# Ma trận E
print("E = np.asmatrix(a).T:") # Update print statement to reflect the change
print(E)
print()

# Least squares
print("linalg.lstsq(F, E):")
x, residuals, rank, s = linalg.lstsq(F, E)
print("Nghiệm x:\n", x)
print("Residuals:", residuals)
print("Rank:", rank)
print("Singular values:", s)
print()

# Các phép toán ma trận
print("np.add(A, D):")
print(np.add(A, D))
print()

print("np.subtract(A, D):")
print(np.subtract(A, D))
print()

print("np.divide(A, D):")
print(np.divide(A, D))
print()

print("A @ D:")
print(A @ D)
print()

print("np.multiply(D, A):")
print(np.multiply(D, A))
print()

print("np.dot(A, D):")
print(np.dot(A, D))
print()

print("np.vdot(A, D):")
print(np.vdot(A, D))
print()

# expm và logm
print("linalg.expm(A):")
print(linalg.expm(A))
print()

print("linalg.logm(A):")
print(linalg.logm(A))
print()

linalg.solve(A, b[:, 0:2]):
[[ 0.33333333+2.33333333j  0.        -0.16666667j]
 [-0.11111111-0.11111111j  0.        +0.88888889j]]

E = np.asmatrix(a).T:
[[1]
 [2]
 [3]]

linalg.lstsq(F, E):
Nghiệm x:
 [[1.]
 [2.]
 [3.]]
Residuals: []
Rank: 3
Singular values: [1. 1. 1.]

np.add(A, D):
[[ 8  6]
 [ 4 12]]

np.subtract(A, D):
[[0 0]
 [0 0]]

np.divide(A, D):
[[1. 1.]
 [1. 1.]]

A @ D:
[[22 30]
 [20 42]]

np.multiply(D, A):
[[16  9]
 [ 4 36]]

np.dot(A, D):
[[22 30]
 [20 42]]

np.vdot(A, D):
65

linalg.expm(A):
[[ 657.82328195 1179.93477479]
 [ 786.6231832  1444.44646515]]

linalg.logm(A):
[[1.22257832 0.66782266]
 [0.44521511 1.66779343]]



In [ ]:
import numpy as np

# Khởi tạo ma trận A
A = np.array([[0, 1], [1, 0]])
print("A =")
print(A)

# Lũy thừa lần đầu tiên
temp = A.dot(A)
print("\nA^2 =")
print(temp)

# Tính các lũy thừa tiếp theo đến bậc k
k = 6
for i in range(k - 2):
    temp = temp.dot(A)
    print(f"\nA^{i+3} =")
    print(temp)



A =
[[0 1]
 [1 0]]

A^2 =
[[1 0]
 [0 1]]

A^3 =
[[0 1]
 [1 0]]

A^4 =
[[1 0]
 [0 1]]

A^5 =
[[0 1]
 [1 0]]

A^6 =
[[1 0]
 [0 1]]


In [ ]:
import numpy as np

# Khởi tạo ma trận B
B = np.array([[0, -1], [-1, 0]])
print("B =")
print(B)

# Lũy thừa lần đầu
temp = B.dot(B)
print("\nB^2 =")
print(temp)

# Tính các lũy thừa tiếp theo đến bậc k
k = 5
for i in range(k - 2):
    temp = temp.dot(B)
    print(f"\nB^{i+3} =")
    print(temp)
    print('---')



B =
[[ 0 -1]
 [-1  0]]

B^2 =
[[1 0]
 [0 1]]

B^3 =
[[ 0 -1]
 [-1  0]]
---

B^4 =
[[1 0]
 [0 1]]
---

B^5 =
[[ 0 -1]
 [-1  0]]
---


In [ ]:
import numpy as np

# Khởi tạo ma trận hội tụ C
C = np.array([
    [1,   0,   0],
    [0, 0.5,   1],
    [0,   0, 0.5]
])
print("Ma trận C:")
print(C)

# Tính C^2
temp = C.dot(C)
print("\nC^2 =")
print(temp)

# Tính C^T với T lớn
k = 1000
for i in range(k - 2):  # đã tính C^2 nên chỉ lặp k-2 lần nữa
    temp = temp.dot(C)

print("\nC^1000 ≈")
print(temp)

# Tính thêm 1000 lần nữa
for i in range(k - 1):
    temp = temp.dot(C)

print("\nC^2000 ≈")
print(temp)


Ma trận C:
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]

C^2 =
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]

C^1000 ≈
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 9.33263619e-302 1.86652724e-298]
 [0.00000000e+000 0.00000000e+000 9.33263619e-302]]

C^2000 ≈
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

# Ma trận M đầu tiên
M = np.array([[0.8, 0.3], [0.2, 0.7]])

# M^2
MM = M.dot(M)
print("M^2 =")
print(MM)

# M^3
MM = MM.dot(M)
print("\nM^3 =")
print(MM)

# M^100
for i in range(100):
    MM = MM.dot(M)
print("\nM^103 ≈")
print(MM)


M^2 =
[[0.7  0.45]
 [0.3  0.55]]

M^3 =
[[0.65  0.525]
 [0.35  0.475]]

M^103 ≈
[[0.6 0.6]
 [0.4 0.4]]


In [ ]:
import numpy as np
from scipy import linalg

# Khởi tạo ma trận M
M = np.array([[0.8, 0.3], [0.2, 0.7]])

# Phân tích LU
P, L, U = linalg.lu(M)

# In các ma trận P, L, U
print("Ma trận P:")
print(P)
print("\nMa trận L:")
print(L)
print("\nMa trận U:")
print(U)

# Kiểm tra tích L*U có bằng M (hay P.T @ M) không
print("\nTích L.dot(U):")
print(L.dot(U))

print("\nSo sánh P.dot(L.dot(U)) với M:")
print(np.allclose(P.dot(L.dot(U)), M))  # True nếu gần bằng



Ma trận P:
[[1. 0.]
 [0. 1.]]

Ma trận L:
[[1.   0.  ]
 [0.25 1.  ]]

Ma trận U:
[[0.8   0.3  ]
 [0.    0.625]]

Tích L.dot(U):
[[0.8 0.3]
 [0.2 0.7]]

So sánh P.dot(L.dot(U)) với M:
True


In [ ]:
import numpy as np

# Khởi tạo ma trận A
A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])

# Tính A^2
temp = A.dot(A)
print("A^2 =")
print(temp)

# Tính A^3
temp = temp.dot(A)
print("\nA^3 =")
print(temp)



A^2 =
[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]

A^3 =
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [ ]:
import numpy as np

# Khởi tạo ma trận A
A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])

sumA = A.copy()  # Khởi tạo tổng bằng A
temp = A.dot(A)  # Tính A^2
k = 3
sumA = sumA + temp  # Cộng A + A^2

for i in range(1, k - 1):
    temp = temp.dot(A)  # Tính tiếp các lũy thừa A^3, A^4,...
    sumA = sumA + temp  # Cộng vào tổng

print("Lũy thừa cao nhất (A^3):")
print(temp)

print("\nTổng A + A^2 + A^3:")
print(sumA)



Lũy thừa cao nhất (A^3):
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]

Tổng A + A^2 + A^3:
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


# **bài tập về nhà:**

câu 1:

In [ ]:
import numpy as np

# a. Chọn ma trận 3x3 khả nghịch
A = np.array([[2, 1, 3],
              [1, 0, 2],
              [4, 1, 8]])

# Kiểm tra khả nghịch (det != 0)
det_A = np.linalg.det(A)
print("Định thức của ma trận A:", det_A)

if det_A != 0:
    print("Ma trận A khả nghịch")
else:
    print("Ma trận A không khả nghịch")

# Tính ma trận nghịch đảo
A_inv = np.linalg.inv(A)
print("Ma trận nghịch đảo A_inv:")
print(A_inv)

# b. Nhập họ tên hoặc mã số sinh viên (ví dụ nhập chuỗi)
student_code = input("Nhập họ tên hoặc mã số sinh viên: ")

# c. Mã hóa: chuyển chuỗi thành vector số (mã ASCII) và nhân với A
# Giả sử mỗi ký tự thành 1 số, đưa vào vector cột 3 phần tử (nếu không đủ thêm 0)
def encode(text, matrix):
    # Chuyển text thành list mã ASCII
    ascii_vals = [ord(c) for c in text]
    # Chia thành nhóm 3 phần tử
    encoded_blocks = []
    for i in range(0, len(ascii_vals), 3):
        block = ascii_vals[i:i+3]
        # Nếu thiếu, thêm 0 để đủ 3 phần tử
        while len(block) < 3:
            block.append(0)
        vec = np.array(block).reshape(3,1)
        encoded_vec = matrix.dot(vec)
        encoded_blocks.append(encoded_vec)
    return encoded_blocks

encoded_blocks = encode(student_code, A)
print("\nCác block mã hóa:")
for block in encoded_blocks:
    print(block.flatten())

# d. Giải mã: nhân ma trận nghịch đảo với từng block mã hóa
def decode(encoded_blocks, inv_matrix):
    decoded_chars = []
    for block in encoded_blocks:
        decoded_vec = inv_matrix.dot(block)
        # Làm tròn và chuyển về ký tự
        decoded_vec_rounded = np.rint(decoded_vec).astype(int).flatten()
        for val in decoded_vec_rounded:
            if val != 0:
                decoded_chars.append(chr(val))
    return ''.join(decoded_chars)

decoded_text = decode(encoded_blocks, A_inv)
print("\nGiải mã (giải mã chuỗi):")
print(decoded_text)


Định thức của ma trận A: -1.0
Ma trận A khả nghịch
Ma trận nghịch đảo A_inv:
[[ 2.  5. -2.]
 [ 0. -4.  1.]
 [-1. -2.  1.]]
Nhập họ tên hoặc mã số sinh viên: 2474802016850

Các block mã hóa:
[317 160 692]
[304 148 648]
[295 148 640]
[323 160 696]
[ 96  48 192]

Giải mã (giải mã chuỗi):
2474802016850


câu 2:

In [ ]:
from fractions import Fraction

def continued_fraction(coeffs):
    # Bắt đầu từ cuối
    result = Fraction(coeffs[-1])
    for a in reversed(coeffs[:-1]):
        result = a + Fraction(1, result)
    return result

# Ví dụ: phân số 8/3 = [2, 1, 2] hoặc [3,1,2] tùy dạng
coeffs = [3, 1, 2]
frac = continued_fraction(coeffs)
print(f"Phân số từ liên phân số {coeffs} là: {frac} = {float(frac)}")


Phân số từ liên phân số [3, 1, 2] là: 11/3 = 3.6666666666666665
