bai tap tai lop


In [8]:
def sgn_by_def(sigma):
    count = 0
    n = len(sigma)
    for i in range(n):
        for j in range(i+1, n):
            if sigma[i] > sigma[j]:
                count += 1
    return (-1)**count


In [7]:
from itertools import permutations
n = 3
X = []
for i in range(1, n+1):
    X.append(i)
Sn = list(permutations(X))  # tạo hoán vị của tập X
print(Sn)


[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [13]:
from itertools import permutations
import numpy as np # Import the numpy library with the alias np

def sgn_by_def(sigma):
    count = 0
    n = len(sigma)
    for i in range(n):
        for j in range(i+1, n):
            if sigma[i] > sigma[j]:
                count += 1
    return (-1)**count

def phatsinh_dinhthuc(n):
    X = []
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))      # tạo tất cả các hoán vị của tập {1, ..., n}
    dinhthuc = ""

    for sn in Sn:                   # duyệt từng hoán vị
        sigma = np.array([1])
        sigma.resize([n])           # khởi tạo mảng sigma độ dài n
        product = ""

        for i in range(1, n+1):     # xây dựng chuỗi biểu thức "aij"
            sigma[sn.index(i)] = i
            product = product + "a" + str(i) + str(sn.index(i)+1)

        dau = sgn_by_def(sigma)     # tính dấu của hoán vị

        if (dau != 1):
            product = " - " + product
        else:
            product = " + " + product

        dinhthuc = dinhthuc + product

    return dinhthuc
print("Định thức cấp 2:")
print(phatsinh_dinhthuc(2))

print("\nĐịnh thức cấp 3:")
print(phatsinh_dinhthuc(3))

Định thức cấp 2:
 + a11a22 - a12a21

Định thức cấp 3:
 + a11a22a33 - a11a23a32 - a12a21a33 + a13a21a32 + a12a23a31 - a13a22a31


In [16]:
matran = np.array([[3,5,-8],
                   [4,12,-1],
                   [2,5,3]])
print(matran)


[[ 3  5 -8]
 [ 4 12 -1]
 [ 2  5  3]]


In [17]:
import numpy as np
from scipy import linalg

A = np.array([[4, -2], [3, -5]])
A1 = np.array([[10, -2], [11, -5]])  # Thay cột 1 bằng vế phải
A2 = np.array([[4, 10], [3, 11]])    # Thay cột 2 bằng vế phải

detA = linalg.det(A)
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)

print(detA, detA1, detA2)


-14.0 -28.0 14.000000000000004


In [18]:
import numpy as np
from scipy import linalg
from itertools import permutations

# Hàm tính định thức theo định nghĩa (Laplace)
def tinhtoan_dinhthuc(A):
    n = len(A)
    perm = list(permutations(range(n)))
    det = 0
    for sigma in perm:
        sign = (-1) ** sum(i < j and sigma[i] > sigma[j] for i in range(n) for j in range(i+1, n))
        prod = 1
        for i in range(n):
            prod *= A[i][sigma[i]]
        det += sign * prod
    return det

# Khai báo ma trận A và các ma trận thay thế
A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

A1 = np.array([[1, 2, -3],
               [3, -2, 1],
               [2, -4, 4]])

A2 = np.array([[-1, 1, -3],
               [2, 3, 1],
               [3, 2, 4]])

A3 = np.array([[-1, 2, 1],
               [2, -2, 3],
               [3, -4, 2]])

print("🔸 Dùng scipy.linalg.det():")
detA = linalg.det(A)
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
detA3 = linalg.det(A3)

if detA != 0:
    x = detA1 / detA
    y = detA2 / detA
    z = detA3 / detA
    print("Nghiệm: x =", x, ", y =", y, ", z =", z)
else:
    print("Hệ phương trình vô nghiệm hoặc vô định.")

print("\n🔸 Dùng tinhtoan_dinhthuc():")
detA = tinhtoan_dinhthuc(A)
detA1 = tinhtoan_dinhthuc(A1)
detA2 = tinhtoan_dinhthuc(A2)
detA3 = tinhtoan_dinhthuc(A3)

if detA != 0:
    x = detA1 / detA
    y = detA2 / detA
    z = detA3 / detA
    print("Nghiệm: x =", x, ", y =", y, ", z =", z)
else:
    print("Hệ phương trình vô nghiệm hoặc vô định.")


🔸 Dùng scipy.linalg.det():
Hệ phương trình vô nghiệm hoặc vô định.

🔸 Dùng tinhtoan_dinhthuc():
Hệ phương trình vô nghiệm hoặc vô định.


In [19]:
import sympy as sp

def dientich_tamgiac(A, B, C):
    # Tạo ma trận 3x3 với cột thứ 3 toàn số 1
    TG = sp.Matrix([
        [A[0], A[1], 1],
        [B[0], B[1], 1],
        [C[0], C[1], 1]
    ])

    # Diện tích tam giác = 1/2 * |định thức|
    S = sp.Rational(1, 2) * abs(TG.det())
    return S

# Ví dụ: A(1, 0), B(4, 3), C(2, 2)
A


array([[-1,  2, -3],
       [ 2, -2,  1],
       [ 3, -4,  4]])

In [20]:
from sympy import Matrix, Rational

def thetich_tu_dien(A, B, C, D):
    # Tạo ma trận 4x4 từ 4 điểm A, B, C, D
    M = Matrix([
        [A[0], A[1], A[2], 1],
        [B[0], B[1], B[2], 1],
        [C[0], C[1], C[2], 1],
        [D[0], D[1], D[2], 1]
    ])
    # Thể tích = 1/6 * |định thức|
    V = Rational(1, 6) * abs(M.det())
    return V

# Ví dụ: 4 điểm trong không gian
A = (0, 4, 1)
B = (4, 0, 0)
C = (3, 5, 2)
D = (2, 2, 5)

# Tính thể tích
V = thetich_tu_dien(A, B, C, D)
print("Thể tích của tứ diện là:", V)


Thể tích của tứ diện là: 12


In [21]:
from sympy import *

# Khai báo biến
x, y, z = symbols('x y z')

# Các điểm
A = Matrix([-1, 3, 2])
B = Matrix([0, 1, 0])
C = Matrix([-2, 0, 1])

# Vector AB và AC
AB = B - A
AC = C - A

# Tích có hướng AB x AC
n = AB.cross(AC)  # vector pháp tuyến

# Phương trình mặt phẳng: n . (X - A) = 0
X = Matrix([x, y, z])
eq = Eq(n.dot(X - A), 0)
print("Phương trình mặt phẳng là:")
print(eq)


Phương trình mặt phẳng là:
Eq(-4*x + 3*y - 5*z - 3, 0)


In [22]:
from sympy import Matrix, symbols, init_printing

init_printing()

A = Matrix([
    [2, 3, 1],
    [4, 1, -3],
    [1, 2, 0]
])
cofactor_matrix = A.cofactor_matrix()
adjoint_matrix = cofactor_matrix.transpose()
print("Ma trận A:")
print(A)

print("\nMa trận hệ số kép (Cofactor matrix):")
print(cofactor_matrix)

print("\nMa trận liên hợp (Adjoint matrix):")
print(adjoint_matrix)

Ma trận A:
Matrix([[2, 3, 1], [4, 1, -3], [1, 2, 0]])

Ma trận hệ số kép (Cofactor matrix):
Matrix([[6, -3, 7], [2, -1, -1], [-10, 10, -10]])

Ma trận liên hợp (Adjoint matrix):
Matrix([[6, 2, -10], [-3, -1, 10], [7, -1, -10]])


In [23]:
from sympy import symbols, Matrix, Eq, simplify, solve, pprint

# Bước 1: Khai báo biến x, y
x, y = symbols('x y')

# Bước 2: Nhập 3 điểm (A, B, C) thuộc đường tròn
# Ví dụ: A = (1, 1), B = (2, 4), C = (5, 3)
A = (1, 1)
B = (2, 4)
C = (5, 3)

# Bước 3: Lập ma trận định thức bậc 5 theo phương trình tổng quát đường tròn
# Mỗi hàng tương ứng (x^2 + y^2, x, y, 1)
def circle_matrix(p):
    xi, yi = p
    return [xi**2 + yi**2, xi, yi, 1]

# Tạo ma trận 4x4 (gồm biến (x, y) và 3 điểm A, B, C)
M = Matrix([
    [x**2 + y**2, x, y, 1],
    circle_matrix(A),
    circle_matrix(B),
    circle_matrix(C)
])

# Bước 4: Lập phương trình = định thức = 0
circle_eq = Eq(M.det(), 0)

# Bước 5: Hiển thị kết quả
print("Phương trình đường tròn đi qua 3 điểm:")
pprint(simplify(circle_eq))


Phương trình đường tròn đi qua 3 điểm:
    2              2                
10⋅x  - 60⋅x + 10⋅y  - 40⋅y + 80 = 0
