Câu 1

In [1]:
import numpy as np
from numpy.linalg import inv, solve, det, eig, matrix_rank, norm
from math import acos, degrees

# Câu 1a
print("Câu 1a:")
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
print("A + B =", A + B)
print("3A - 2B =", 3*A - 2*B)

# Câu 1b
print("\nCâu 1b:")
dot_product = np.dot(A, B)
angle = degrees(acos(dot_product / (norm(A) * norm(B))))
print("A · B =", dot_product)
print("Góc giữa A và B ≈", round(angle, 3), "độ")

# Câu 1c
print("\nCâu 1c:")
C = np.array([
    [1, 2, -1],
    [0, 3, 4],
    [2, -1, 0]
])
CtC = C.T @ C
print("Cᵀ × C =\n", CtC)


Câu 1a:
A + B = [3 3 1 5]
3A - 2B = [  4 -11  13 -10]

Câu 1b:
A · B = -8
Góc giữa A và B ≈ 108.376 độ

Câu 1c:
Cᵀ × C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


Câu 2

In [2]:
# Câu 2a
print("\nCâu 2a:")
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])
N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])
MN = M @ N
print("M × N =\n", MN)

# Câu 2b
print("\nCâu 2b:")
det_M = det(M)
print("det(M) =", det_M)

# Câu 2c
print("\nCâu 2c:")
rank_N = matrix_rank(N)
print("rank(N) =", rank_N)



Câu 2a:
M × N =
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

Câu 2b:
det(M) = 6.66133814775094e-16

Câu 2c:
rank(N) = 2


Câu 3

In [3]:

# Câu 3a
print("\nCâu 3a:")
P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])
if det(P) != 0:
    P_inv = inv(P)
    print("P khả nghịch. P⁻¹ =\n", P_inv)
else:
    print("P không khả nghịch.")

# Câu 3b
print("\nCâu 3b:")
b3 = np.array([4, 7, 9, 5])
x3 = P_inv @ b3
print("Nghiệm x =", x3)

# Câu 3c
print("\nCâu 3c:")
check_b3 = P @ x3
print("P·x =", check_b3)
print("b =", b3)


Câu 3a:
P khả nghịch. P⁻¹ =
 [[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

Câu 3b:
Nghiệm x = [0.46511628 2.10465116 1.65116279 0.96511628]

Câu 3c:
P·x = [4. 7. 9. 5.]
b = [4 7 9 5]


Câu 4

In [4]:

# Câu 4a
print("\nCâu 4a:")
Q = np.array([
    [4, -1, 0],
    [1, 3, -2],
    [0, 1, 2]
])
e_vals, e_vecs = eig(Q)
print("Giá trị riêng:", e_vals)

# Câu 4b
print("\nCâu 4b:")
print("Vector riêng (theo cột):\n", e_vecs)

# Câu 4c
print("\nCâu 4c:")
for i in range(len(e_vals)):
    v = e_vecs[:, i]
    v_unit = v / norm(v)
    print(f"Vector riêng v{i+1} chuẩn hóa =", v_unit)


Câu 4a:
Giá trị riêng: [3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]

Câu 4b:
Vector riêng (theo cột):
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]

Câu 4c:
Vector riêng v1 chuẩn hóa = [0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Vector riêng v2 chuẩn hóa = [-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
Vector riêng v3 chuẩn hóa = [-0.26206044+0.31354813j -0.78166743+0.j         -0.21963176-0.41685708j]


Câu 5

In [5]:
# Câu 5a
print("\nCâu 5a:")
R = np.array([
    [1, -2, 3],
    [2, 0, 1],
    [-1, 1, 4]
])
b5 = np.array([10, 8, 7])
x5 = solve(R, b5)
print("Nghiệm x =", x5)

# Câu 5b
print("\nCâu 5b:")
if det(R) != 0:
    R_inv = inv(R)
    x_check = R_inv @ b5
    print("R⁻¹ =\n", R_inv)
    print("Nghiệm bằng R⁻¹ · b =", x_check)
    print("So sánh nghiệm:", np.allclose(x5, x_check))
else:
    print("R không khả nghịch.")

# Câu 5c
print("\nCâu 5c:")
fro_R = norm(R, 'fro')
print("Chuẩn Frobenius của R =", fro_R)


Câu 5a:
Nghiệm x = [2.7826087  0.04347826 2.43478261]

Câu 5b:
R⁻¹ =
 [[-0.04347826  0.47826087 -0.08695652]
 [-0.39130435  0.30434783  0.2173913 ]
 [ 0.08695652  0.04347826  0.17391304]]
Nghiệm bằng R⁻¹ · b = [2.7826087  0.04347826 2.43478261]
So sánh nghiệm: True

Câu 5c:
Chuẩn Frobenius của R = 6.082762530298219
