BÀI TẬP TẠI LỚP

In [5]:
def scare(a,v):
  return [a*vi for vi in v]
vi = [3,5,7]
print(scare(10,v))

[30, 50, 70]


In [6]:
def sumvector(a,v):
  return [vi+wi for (vi,wi) in zip(a,v)]
a = [3,5,7]
v = [2,4,6]

print(sumvector(a,v))


[5, 9, 13]


In [7]:
import math

def dotvector(v1, v2):
    return sum(x * y for x, y in zip(v1, v2))

def lenvector(v):
    return math.sqrt(dotvector(v, v))

w = [3, 4]
print(lenvector(w))

5.0


In [9]:
import numpy as np

# Phần 1
scores = np.array([-1, 1, 2, -3, 5, -4])
print("scores:", scores)

print("scores >= 0:", scores >= 0)
print("scores < 0:", scores < 0)

# Thêm default='' để đảm bảo dtype cho đầu ra là string
labels1 = np.select([scores >= 0, scores < 0], ['so duong', 'so am'], default='')
print("Phân loại (>=0 và <0):", labels1)

print("\n---\n")

# Phần 2
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print("scores:", scores)

# Thêm default='' để đảm bảo dtype cho đầu ra là string
labels2 = np.select(
    [scores > 0, scores == 0, scores < 0],
    ['so duong', 'so 0', 'so am'],
    default=''
)
print("Phân loại (>0, ==0, <0):", labels2)

scores: [-1  1  2 -3  5 -4]
scores >= 0: [False  True  True False  True False]
scores < 0: [ True False False  True False  True]
Phân loại (>=0 và <0): ['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']

---

scores: [-1  1  2  0 -3  5  0 -4]
Phân loại (>0, ==0, <0): ['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


In [11]:
# STT 1: Import thư viện
import numpy as np
from scipy import linalg, sparse

# STT 2: Ma trận D
# Thay np.mat bằng np.asmatrix
D = np.asmatrix([[3, 4], [5, 6]])
print("Ma trận D:\n", D)

# STT 3: Ma trận ngẫu nhiên C (5x7)
# Thay np.mat bằng np.asmatrix
C = np.asmatrix(np.random.random((5, 7)))
print("\nMa trận C (5x7 - ngẫu nhiên):\n", C)

# STT 4: Ma trận ngẫu nhiên A (2x2)
# Thay np.mat bằng np.asmatrix
A = np.asmatrix(np.random.random((2, 2)))
print("\nMa trận A (2x2 - ngẫu nhiên):\n", A)

# STT 5: Mảng phức b, chuyển sang ma trận B
b = np.array([(1+5j, 2j, 3j), (4, 5, 6)])
B = np.asmatrix(b)

# STT 6: In mảng b và ma trận B
print("\nMảng b:\n", b)
print("\nMa trận B (từ b):\n", B)

# STT 7: Chuyển vị ma trận A
print("\nA.T (chuyển vị A):\n", A.T)

# STT 7 tiếp: Ma trận nghịch đảo A
# Sử dụng .I cho ma trận là cách thông thường với np.matrix
print("\nMa trận nghịch đảo A (A.I):\n", A.I)
print("\nMa trận nghịch đảo A (linalg.inv):\n", linalg.inv(A))

# STT 8: Ma trận dưới từ đường chéo
M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])
M_lower = np.tril(M)
print("\nMa trận M:\n", M)
print("\nMa trận dưới từ đường chéo (M_lower):\n", M_lower)

# STT 9: Ma trận trên từ đường chéo
M_upper = np.triu(M)
print("\nMa trận trên từ đường chéo (M_upper):\n", M_upper)

# STT 10: Vector đường chéo và ma trận đường chéo
v_diag = np.diag(M)
print("\nVector đường chéo (v_diag):\n", v_diag)

M_diag = np.diag(v_diag)
print("\nMa trận đường chéo từ vector (M_diag):\n", M_diag)

Ma trận D:
 [[3 4]
 [5 6]]

Ma trận C (5x7 - ngẫu nhiên):
 [[0.48011331 0.9647095  0.18964272 0.43418768 0.32594764 0.46023122
  0.84242726]
 [0.52760904 0.15856888 0.36775574 0.21553621 0.06320154 0.85835857
  0.6714982 ]
 [0.69135732 0.49526936 0.4513114  0.91187083 0.21684343 0.14784599
  0.50654326]
 [0.09761222 0.83503275 0.59580963 0.02272083 0.418582   0.52025893
  0.68715844]
 [0.17251356 0.01880104 0.80015238 0.48174685 0.65813323 0.24156531
  0.90358872]]

Ma trận A (2x2 - ngẫu nhiên):
 [[0.08863842 0.50178392]
 [0.18444469 0.24769877]]

Mảng b:
 [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]

Ma trận B (từ b):
 [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]

A.T (chuyển vị A):
 [[0.08863842 0.18444469]
 [0.50178392 0.24769877]]

Ma trận nghịch đảo A (A.I):
 [[-3.50869232  7.10784855]
 [ 2.61268828 -1.25557729]]

Ma trận nghịch đảo A (linalg.inv):
 [[-3.50869232  7.10784855]
 [ 2.61268828 -1.25557729]]

Ma trận M:
 [[-1  3  2]
 [ 0 -2  1]
 [ 1  5 -2]]

Ma trận dưới từ đườ

In [12]:
import numpy as np

A = np.reshape(np.arange(36.0), (6, 6))
print(A)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [13]:
I6 = np.identity(6)
print(I6)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [14]:
A = A + I6
print(A)


[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [15]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)


[ 71. 198. 325. 452. 579. 706.]


In [16]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)


[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


In [17]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0.], [5., 1.], [6., 0.]])
G = A.dot(F)
print(F)


[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]


In [18]:
import numpy as np
A = np.array([[1,1], [1,0]])
b = np.array([1, 0])
n = 10

for i in range(n):
    b = A.dot(b)
    print(b)


[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [20]:
# Import the necessary library for symbolic math (assuming sympy based on 'sp')
# If you don't have sympy installed, run: !pip install sympy
import sympy as sp

# Define the symbolic variables x1, x2, x3, and x4
x1, x2, x3, x4 = sp.symbols('x1 x2 x3 x4')

pt1 = x4 + 610 - 450 - x1        # => x4 + 160 - x1 = 0
pt2 = x1 + 400 - x2 - 640        # => x1 - x2 - 240 = 0
pt3 = x2 + 600 - x3              # => x2 + 600 - x3 = 0
pt4 = x3 - x4 - 520              # => x3 - x4 - 520 = 0

# Solve the system of equations
nghiem = sp.solve((pt1, pt2, pt3, pt4), (x1, x2, x3, x4))

# Print the solution
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [26]:
A = np.matrix([[-1, 0, 0, 1],
               [1, -1, 0, 0],
               [0, 1, -1, 0],
               [0, 0, 1, -1]])
print(A)

[[-1  0  0  1]
 [ 1 -1  0  0]
 [ 0  1 -1  0]
 [ 0  0  1 -1]]


# BÀI TẬP VỀ NHÀ

BÀI 1

In [29]:
# CÂU1:
import numpy as np

A = np.array([[1, -1], [1, 1]])
b = np.array([-2, 6])
solution = np.linalg.solve(A, b)
print("Giao điểm (x, y):", solution)  # Kết quả: (2.0, 4.0)
A = np.array([[1, -1, 0], [0, 1, 0], [0, 0, 1]])
b = np.array([2, -2, 3])
solution = np.linalg.solve(A, b)
print("Giao điểm (x, y, z):", solution)  # Kết quả: (0.0, -2.0, 3.0)
roots = [1, 2, 3]
coefficients = np.poly(roots)
print("Hệ số đa thức:", coefficients)  # [1, -6, 11, -6] tương ứng x³ -6x² +11x -6
A = np.array([[1, -1], [1, 1]])
b = np.array([-2, 6])
solution = np.linalg.solve(A, b)
print("Giao điểm (x, y):", solution)  # Kết quả: (2.0, 4.0)
A = np.array([[1, -1, 0], [0, 1, 0], [0, 0, 1]])
b = np.array([2, -2, 3])
solution = np.linalg.solve(A, b)
print("Giao điểm (x, y, z):", solution)  # Kết quả: (0.0, -2.0, 3.0)
roots = [1, 2, 3]
coefficients = np.poly(roots)
print("Hệ số đa thức:", coefficients)  # [1, -6, 11, -6] tương ứng x³ -6x² +11x -6

Giao điểm (x, y): [2. 4.]
Giao điểm (x, y, z): [ 0. -2.  3.]
Hệ số đa thức: [ 1. -6. 11. -6.]
Giao điểm (x, y): [2. 4.]
Giao điểm (x, y, z): [ 0. -2.  3.]
Hệ số đa thức: [ 1. -6. 11. -6.]


BÀI 2:


In [30]:
from sympy import symbols, Eq, solve

x, y = symbols('x y')
eq1 = Eq(x - y, -2)
eq2 = Eq(x + y, 6)
solution = solve((eq1, eq2), (x, y))
print(solution)  # {x: 2, y: 4}
x, y, z = symbols('x y z')
eq1 = Eq(x - y, 2)
eq2 = Eq(y, -2)
eq3 = Eq(z, 3)
solution = solve((eq1, eq2, eq3), (x, y, z))
print(solution)  # {x: 0, y: -2, z: 3}
from sympy import poly, roots

x = symbols('x')
p = poly((x-1)*(x-2)*(x-3), x)
print("Đa thức:", p.as_expr())  # x³ - 6x² + 11x - 6

{x: 2, y: 4}
{x: 0, y: -2, z: 3}
Đa thức: x**3 - 6*x**2 + 11*x - 6


BÀI 3:


In [31]:
def matrix_power(F, k):
    result = np.eye(2, dtype=int)  # Ma trận đơn vị
    for _ in range(k):
        result = np.dot(result, F)
    return result

F = np.array([[1,1],[0,0]])
k = 5
F_k = matrix_power(F, k)
print(f"F^{k} =\n{F_k}")
# Kết quả sẽ chứa Fib(k+1), Fib(k), Fib(k-1)

F^5 =
[[1 1]
 [0 0]]
