In [1]:
import numpy as np
u = np.array([2, -1, 5, 0])
v = np.array([4, 3, 1, -1])
w = np.array([-6, 2, 0, 3])

x = 2*u - (v + 3*w)
print(x)

x = 0.5 * (2*u - v - 3*w)
print(x)

[ 18 -11   9  -8]
[ 9.  -5.5  4.5 -4. ]


In [2]:
import numpy as np
from numpy import linalg

A = np.array([[0, -1, 3],
              [1, 1, 1],
              [4, 2, 2]])
B = np.array([-1, -2, -2])

X = np.linalg.solve(A, B)
print(X)


[ 1. -2. -1.]


In [3]:
import numpy as np
from numpy import linalg as LA

# Khởi tạo ma trận
A = np.matrix([[1, 0], [0, 0]])
B = np.matrix([[0, 0], [0, 1]])

# Phương pháp 1: Kiểm tra khả nghịch bằng inv()
print("Phương pháp 1: Kiểm tra bằng inv()")

try:
    print("inv(A):")
    print(LA.inv(A))
except LA.LinAlgError as e:
    print("inv(A) error:", e)

try:
    print("inv(B):")
    print(LA.inv(B))
except LA.LinAlgError as e:
    print("inv(B) error:", e)

try:
    print("inv(A + B):")
    print(LA.inv(A + B))
except LA.LinAlgError as e:
    print("inv(A+B) error:", e)

# Phương pháp 2: Tính định thức bằng det()
print("\nPhương pháp 2: Tính bằng det()")

print("det(A):", LA.det(A))
print("det(B):", LA.det(B))
print("det(A + B):", LA.det(A + B))


Phương pháp 1: Kiểm tra bằng inv()
inv(A):
inv(A) error: Singular matrix
inv(B):
inv(B) error: Singular matrix
inv(A + B):
[[1. 0.]
 [0. 1.]]

Phương pháp 2: Tính bằng det()
det(A): 0.0
det(B): 0.0
det(A + B): 1.0


In [4]:
import sympy as sp

# Tạo các biến hình thức
x, y = sp.symbols('x y')
x1, y1 = sp.symbols('x1 y1')
x2, y2 = sp.symbols('x2 y2')
c = sp.symbols('c')

# Khai báo các ma trận đối xứng
A = sp.Matrix([[x, y], [y, x]])
A1 = sp.Matrix([[x1, y1], [y1, x1]])
A2 = sp.Matrix([[x2, y2], [y2, x2]])

# 1. Chuyển vị của A1
print("A1.T:")
print(A1.T)

# 2. Chuyển vị của A1 + A2
print("\n(A1 + A2).T:")
print((A1 + A2).T)

# 3. So sánh chuyển vị của (A1 + A2) với A1 + A2
print("\nIs (A1 + A2).T equal to A1 + A2?")
print(((A1 + A2).T).equals(A1 + A2))

# 4. Nhân A với số thực c
print("\nc * A:")
print(c * A)

# 5. Kiểm tra tính đối xứng của c*A
print("\nIs (c*A).T equal to c*A?")
print(((c * A).T).equals(c * A))


A1.T:
Matrix([[x1, y1], [y1, x1]])

(A1 + A2).T:
Matrix([[x1 + x2, y1 + y2], [y1 + y2, x1 + x2]])

Is (A1 + A2).T equal to A1 + A2?
True

c * A:
Matrix([[c*x, c*y], [c*y, c*x]])

Is (c*A).T equal to c*A?
True


In [5]:
import numpy as np
from numpy import linalg as LA

# Cơ sở 3 vector
v1 = np.array([1, 2, 3])
v2 = np.array([0, 1, 2])
v3 = np.array([-1, 0, 1])

# Tạo ma trận A có 3 vector là cột
A = np.column_stack([v1, v2, v3])

# Trường hợp a: b = (1, 1, 1)
b1 = np.array([1, 1, 1])
try:
    x1 = LA.solve(A, b1)
    print("a. Hệ có nghiệm, vector là tổ hợp tuyến tính:")
    print(x1)
except LA.LinAlgError as e:
    print("a. Hệ vô nghiệm:", e)

# Trường hợp b: b = (1, -2, 2)
b2 = np.array([1, -2, 2])
try:
    x2 = LA.solve(A, b2)
    print("b. Hệ có nghiệm, vector là tổ hợp tuyến tính:")
    print(x2)
except LA.LinAlgError as e:
    print("b. Hệ vô nghiệm:", e)


a. Hệ có nghiệm, vector là tổ hợp tuyến tính:
[ 5.00000000e-01 -1.66533454e-16 -5.00000000e-01]
b. Hệ có nghiệm, vector là tổ hợp tuyến tính:
[ 3.15251974e+16 -6.30503948e+16  3.15251974e+16]


In [6]:
import sympy as sp

# Khai báo các ẩn
c1, c2, c3 = sp.symbols('c1 c2 c3')

# Hệ phương trình
eq1 = c1 - 2*c3
eq2 = 2*c1 + c2
eq3 = 3*c1 + 2*c2 + c3

# Giải hệ
solution = sp.solve([eq1, eq2, eq3], [c1, c2, c3])
print(solution)


{c1: 0, c2: 0, c3: 0}


In [7]:
import sympy as sp

# Khai báo biến
c1, c2 = sp.symbols('c1 c2')  # c1 ~ a1, c2 ~ a2
u1, u2 = sp.symbols('u1 u2')

# Giải hệ tổng quát
sol1 = sp.solve([c1 + c2 - u1, c1 - c2 - u2], [c1, c2])
print(sol1)


{c1: u1/2 + u2/2, c2: u1/2 - u2/2}


In [8]:
import numpy as np

# Khởi tạo ma trận P: mỗi cột là một điểm (x, y)
P = np.array([
    [0, 0, 3, 3, 1, 1, 2, 2, 1, 1],   # tọa độ x
    [0, 5, 5, 4, 4, 3, 3, 2, 2, 0]    # tọa độ y
])

# Vector dịch chuyển (delta x, delta y)
vecdelta = np.array([4, 2])

# Bước 1: Chuyển vị để mỗi điểm là một dòng
P_T = P.T
print("P.T =\n", P_T)

# Bước 2: Cộng mỗi điểm với vecdelta
P_T_shifted = P_T + vecdelta
print("\nP.T + vecdelta =\n", P_T_shifted)

# Bước 3: Chuyển lại về dạng 2 hàng (x và y)
P_caua = P_T_shifted.T
print("\nP_caua =\n", P_caua)


P.T =
 [[0 0]
 [0 5]
 [3 5]
 [3 4]
 [1 4]
 [1 3]
 [2 3]
 [2 2]
 [1 2]
 [1 0]]

P.T + vecdelta =
 [[4 2]
 [4 7]
 [7 7]
 [7 6]
 [5 6]
 [5 5]
 [6 5]
 [6 4]
 [5 4]
 [5 2]]

P_caua =
 [[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


In [9]:
import numpy as np

# Tập hợp điểm gốc (x, y)
P = np.array([
    [0, 0, 3, 3, 1, 1, 2, 2, 1, 1],
    [0, 5, 5, 4, 4, 3, 3, 2, 2, 0]
])

# Vector dịch chuyển
vecdelta = np.array([4, -2])

# Ma trận biến đổi co giãn
matran_biendoi = np.array([
    [1.0, 0.0],
    [0.0, 2.0]
])

# Biến đổi: (P.T @ scale + vecdelta).T
P_caub = (P.T @ matran_biendoi + vecdelta).T

# In kết quả
print(P_caub)


[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [10]:
import numpy as np

# Dữ liệu gốc
P = np.array([
    [0, 0, 3, 3, 1, 1, 2, 2, 1, 1],
    [0, 5, 5, 4, 4, 3, 3, 2, 2, 0]
])

# Vector dịch chuyển (tọa độ mới gốc: (4, -2))
vecdelta = np.array([4, -2])

# Ma trận biến đổi: đối xứng qua trục y
matran_biendoi = np.array([
    [-1, 0],
    [0, 1]
])

# Áp dụng biến đổi
P_cauc = (P.T @ matran_biendoi + vecdelta).T

# In kết quả
print(P_cauc)


[[ 4  4  1  1  3  3  2  2  3  3]
 [-2  3  3  2  2  1  1  0  0 -2]]


In [11]:
import numpy as np

# Tọa độ ban đầu
P = np.array([
    [0,0,3,3,1,1,2,2,1,1],
    [0,5,5,4,4,3,3,2,2,0]
])

# Vector tịnh tiến
vecdelta = np.array([4, -2])

# Ma trận shearing (L=1.5, M=0)
shear_matrix = np.array([
    [1, 1.5],
    [0, 1]
])

# Thực hiện biến đổi
P_caud = (P.T @ shear_matrix + vecdelta).T

# In kết quả
print(P_caud)


[[ 4.   4.   7.   7.   5.   5.   6.   6.   5.   5. ]
 [-2.   3.   7.5  6.5  3.5  2.5  4.   3.   1.5 -0.5]]


In [12]:
import sympy as sp
from sympy import lambdify

# Khai báo các biến đầu vào
x1, x2, x3 = sp.symbols('x1 x2 x3')
a, b, c = sp.symbols('a b c')   # vector X = (a, b, c)
d, e, f = sp.symbols('d e f')   # vector Y = (d, e, f)
q = sp.symbols('q')             # hệ số vô hướng

# Biểu thức hàm tuyến tính f1
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'sympy')

# Tính f1 cho từng trường hợp
f1_X = f1(a, b, c)
f1_Y = f1(d, e, f)
f1_XplusY = f1(a + d, b + e, c + f)

# Kiểm tra tính cộng: f(X + Y) = f(X) + f(Y)
tinh_cong = (f1_X + f1_Y).equals(f1_XplusY)

# Kiểm tra tính đồng nhất: f(qX + Y) = qf(X) + f(Y)
tinh_dong_nhat = (q*f1_X + f1_Y).equals(f1(q*a + d, q*b + e, q*c + f).expand())

# In kết quả
print("f1(X) =", f1_X)
print("f1(Y) =", f1_Y)
print("f1(X + Y) =", f1_XplusY)
print("f1(X) + f1(Y) == f1(X + Y)?", tinh_cong)
print("q*f1(X) + f1(Y) == f1(q*X + Y)?", tinh_dong_nhat)


f1(X) = a - b + c
f1(Y) = d - e + f
f1(X + Y) = a - b + c + d - e + f
f1(X) + f1(Y) == f1(X + Y)? True
q*f1(X) + f1(Y) == f1(q*X + Y)? True


In [13]:
import sympy as sp
from sympy import lambdify

# Khai báo các biến
x1, x2, x3 = sp.symbols('x1 x2 x3')
a, b, c = sp.symbols('a b c')   # X = (a, b, c)
d, e, f = sp.symbols('d e f')   # Y = (d, e, f)
q = sp.symbols('q')

# Biểu thức f2
bieuthuc2 = 2 * x2 + 3 * x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'sympy')

# Kiểm tra tính đồng nhất: f(qX + Y) == qf(X) + f(Y)
lhs = q * f2(a, b, c) + f2(d, e, f)
rhs = f2(q * a + d, q * b + e, q * c + f)
check = lhs.equals(rhs.expand())

print("q*f2(X) + f2(Y) == f2(q*X + Y)?", check)


q*f2(X) + f2(Y) == f2(q*X + Y)? True


In [14]:
import numpy as np

# Các vector ảnh f(u1), f(u2)
fu1 = np.array([1, 1, 2])
fu2 = np.array([4, 2, 1])

# Tạo biểu thức f(u) = a*fu1 + b*fu2
a, b, x, y = sp.symbols('a b x y')
fu_expr = a*fu1 + b*fu2
print("f(u) theo a, b:")
print(fu_expr)

# Thay a = -5x + 3y, b = 2x - y vào
a_val =_


f(u) theo a, b:
[a + 4*b a + 2*b 2*a + b]


In [16]:
import sympy as sp

# Khai báo các vector cơ sở
v1 = sp.Matrix([-1, 1])
v2 = sp.Matrix([1, 0])

w1 = sp.Matrix([1, 2])
w2 = sp.Matrix([1, 3])

# Định nghĩa ánh xạ f(x, y) = (x - y, x)
def f(vec):
    x, y = vec[0], vec[1]
    retu


In [18]:
import numpy as np
import math
from scipy import linalg as LA

# Tạo ma trận quay góc pi/4
theta = math.pi / 4
cos_t = math.cos(theta)
sin_t = math.sin(theta)

# Ma trận B quay (không chuẩn hóa từng hàng, chỉ đúng góc quay)
B = np.array([
    [cos_t, sin_t],
    [-sin_t, cos_t]
])

print("Ma trận B:")
print(B)

# Kiểm tra trực giao: B^T * B ≈ I
print("B.T @ B:")
print(B.T @ B)

Ma trận B:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
B.T @ B:
[[1.00000000e+00 1.01465364e-17]
 [1.01465364e-17 1.00000000e+00]]


In [24]:
import sympy as sp

x, y, z = sp.symbols('x y z')
a, b, c = sp.symbols('a b c')
f = sp.Matrix([x + y, z + 2, 0])

# Kiểm tính cộng: f(u+v) = f(u) + f(v)?
f1 = f.subs({x: a + x, y: b + y, z: c + z})
f_sum = f.subs({x: a, y: b, z: c}) + f.subs({x: x, y: y, z: z})
print(f1.equals(f_sum))  # False
import numpy as np

# Tập điểm F (ví dụ 10 điểm)
F = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])  # 2x4 điểm: x, y

# Ma trận biến đổi
T = np.array([
    [0, 1],
    [1, -1]
])

# Biến đổi: T * F
F_new = T @ F
print("Tập điểm sau biến đổi:\n", F_new)
import sympy as sp

x, y = sp.symbols('x y')
a, b = sp.symbols('a b')
u = sp.Matrix([x, y])
v = sp.Matrix([a, b])

def O(vec):
    return sp.Matrix([vec[0] - vec[1], vec[0] + 2*vec[1]])

# Tuyến tính nếu: O(u + v) = O(u) + O(v)
is_linear = O(u + v).equals(O(u) + O(v))
print("O có phải ánh xạ tuyến tính không?", is_linear)  # True
import sympy as sp

x, y = sp.symbols('x y')
a, b, c, d, e, f = 1, 4, 3, 0, 0, 0  # Ví dụ: x^2 + 4xy + 3y^2

Q = sp.Matrix([[a, b/2],
               [b/2, c]])

vec = sp.Matrix([x, y])
quad_form = (vec.T * Q * vec)[0]
print("Dạng toàn phương:", quad_form.expand())

False
Tập điểm sau biến đổi:
 [[ 5  6  7  8]
 [-4 -4 -4 -4]]
O có phải ánh xạ tuyến tính không? True
Dạng toàn phương: x**2 + 4.0*x*y + 3*y**2
